# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hey_how_pb2 as hey__how__pb2


class HeyHowServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.heyhow = channel.unary_unary(
                '/hey_how.HeyHowService/heyhow',
                request_serializer=hey__how__pb2.HeyHow.SerializeToString,
                response_deserializer=hey__how__pb2.LetsGo.FromString,
                )


class HeyHowServiceServicer(object):
    """Service definition
    """

    def heyhow(self, request, context):
        """rpc method heyhow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeyHowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'heyhow': grpc.unary_unary_rpc_method_handler(
                    servicer.heyhow,
                    request_deserializer=hey__how__pb2.HeyHow.FromString,
                    response_serializer=hey__how__pb2.LetsGo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hey_how.HeyHowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HeyHowService(object):
    """Service definition
    """

    @staticmethod
    def heyhow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hey_how.HeyHowService/heyhow',
            hey__how__pb2.HeyHow.SerializeToString,
            hey__how__pb2.LetsGo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
